# Generated by Django 5.2.5 on 2025-10-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='preferred_stats',
            field=models.JSONField(blank=True, default=list, verbose_name='선호 통계 목록'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='임시닉네임', max_length=150, unique=True, verbose_name='닉네임'),
            preserve_default=False,
        ),
    ]
