# Generated by Django 5.2.5 on 2025-10-24 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_preferred_stats_alter_user_nickname'),
        ('users', '0003_create_superuser'),
    ]

    operations = [
    ]
